# version: "3.9"

# services:
#   web: 
#     container_name: SUDICOL
#     image: orbitmedia/php:7.3-apache
#     ports:
#       - 8080:80
#     volumes:
#       - .:/var/www/html
version: "3.9"

services:
  web: 
    container_name: SUDICOL
    image: orbitmedia/php:7.3-apache
    depends_on:
      - database
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    networks:
      - sudicol-network
    links:
      - database:mysql
  database:
    container_name: SUDICOL_DB
    command: --default-authentication-plugin=mysql_native_password
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./dum_usuarios.sql:/docker-entrypoint-initdb.d/dum_usuarios.sql
    networks:
      - sudicol-network
    environment:
      - MYSQL_ROOT_PASSWORD=AccesoStockSudicol2023*
      - MYSQL_DATABASE=u682444666_stock
      - MYSQL_USER=u682444666_stock
      - MYSQL_PASSWORD=AccesoStockSudicol2023*
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 250M
      restart_policy:
        condition: on-failure

networks:
  sudicol-network:
    # driver: bridge